# Generated by Django 2.2.4 on 2019-09-04 14:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statustable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Typetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicletable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehnum', models.CharField(max_length=3)),
                ('is_lpr', models.BooleanField(default='False')),
                ('isforpatrol', models.BooleanField(default='False')),
                ('is_active', models.BooleanField(default='False')),
                ('datetaken', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vTrak.Statustable')),
                ('vehtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vTrak.Typetable')),
            ],
        ),
    ]
