# Generated by Django 2.2.4 on 2019-08-28 23:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicletable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehnum', models.CharField(max_length=3)),
                ('vehtype', models.TextField()),
                ('datetaken', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
