# Generated by Django 2.2.4 on 2019-08-29 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vTrak', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statustable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='vehicletable',
            name='is_active',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='vehicletable',
            name='is_lpr',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='vehicletable',
            name='isforpatrol',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='vehicletable',
            name='vehnum',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddField(
            model_name='vehicletable',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vTrak.Statustable'),
        ),
    ]
