# Generated by Django 2.2.4 on 2019-09-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vTrak', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squadtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad', models.CharField(max_length=20)),
                ('squad_desc', models.CharField(max_length=30)),
            ],
        ),
    ]
