# Generated by Django 2.2.4 on 2019-09-11 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vTrak', '0003_activitytable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitytable',
            old_name='whohas',
            new_name='callsign',
        ),
    ]
