# Generated by Django 2.2.4 on 2019-09-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vTrak', '0004_auto_20190911_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytable',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default='2019-09-04 20:23:15'),
            preserve_default=False,
        ),
    ]
